name: Build and release sshpass
on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]
        arch: [386, amd64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        if: matrix.os == 'windows-latest'
        run: |
          choco install make
          choco install mingw
          cd C:\
      - name: Build sshpass
        run: |
          git clone https://github.com/kevinburke/sshpass
          cd sshpass
          ./configure
          make
      - name: Rename
        run: |
          if [ "${{ matrix.os }}" == "windows-latest" ]; then
            if [ "${{ matrix.arch }}" == "386" ]; then
              ren sshpass.exe sshpass-windows-386.exe 
            fi
            if [ "${{ matrix.arch }}" == "amd64" ]; then
              ren sshpass.exe sshpass-windows-amd64.exe
            fi
          elif [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            if [ "${{ matrix.arch }}" == "386" ]; then
              mv sshpass sshpass-linux-386
            fi
            if [ "${{ matrix.arch }}" == "amd64" ]; then
              mv sshpass sshpass-linux-amd64
            fi
          elif [ "${{ matrix.os }}" == "macos-latest" ]; then
            if [ "${{ matrix.arch }}" == "386" ]; then
              mv sshpass sshpass-darwin-386
            fi
            if [ "${{ matrix.arch }}" == "amd64" ]; then
               mv sshpass sshpass-darwin-amd64
            fi
          fi
      - name: Publish Release windows-386
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: JasonEtco/upload-to-release@master
        with:
          args: sshpass-windows-386.exe 
      - name: Publish Release windows-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: JasonEtco/upload-to-release@master
        with:
          args: sshpass-windows-amd64.exe 
      - name: Publish Release linux-386
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: JasonEtco/upload-to-release@master
        with:
          args: sshpass-linux-386
      - name: Publish Release linux-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: JasonEtco/upload-to-release@master
        with:
          args: sshpass-linux-amd64
      - name: Publish Release macos-386
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: JasonEtco/upload-to-release@master
        with:
          args: sshpass-darwin-386
      - name: Publish Release macos-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: JasonEtco/upload-to-release@master
        with:
          args: sshpass-darwin-amd64
